using System;
using System.Collections.Generic;
using System.Text;

namespace Assignment6
{
    class Prob10_URLShortener
    {
        static void Main(string[] args)
        {
            int number = 74561;

            string shortURL = getShortURL(number);
            if (shortURL is null)
            {
                Console.WriteLine("The short url can not be retrieved.");
            }
            else
            {
                Console.WriteLine("The short url generated for id '" + number + "' is: " + shortURL);
            }
            
            
            int id = getId(shortURL);
            if(id == -1)
            {
                Console.WriteLine("The id can not be retrieved.");
            }
            else
            {
                Console.WriteLine("The id generated by the short url '" + shortURL + "' is: " + id);
            }
        }

        static string getShortURL(int id)
        {
            string record = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            string shortUrlinReverse = "";
            string shortUrl= "";
            char value = '\n';

            if(id == 0)
            {
                return null;
            }

            while(id > 0)
            {
                int i = id % 62;
                value = record[i];
                shortUrlinReverse = shortUrlinReverse + value;
                id = id / 62;
            }

            for(int i = shortUrlinReverse.Length-1; i>=0; i--)
            {
                shortUrl = shortUrl + shortUrlinReverse[i];
            }
            return shortUrl;

        }

        static int getId(string url)
        {
            int id = 0;

            if(url is null)
            {
                return -1;
            }

            for (int i = 0; i < url.Length; i++)
            {
                if (url[i] >= 'a' && url[i] <= 'z')
                {
                    id = id * 62 + url[i] - 'a';
                }

                else if (url[i] >= 'A' && url[i] <= 'Z')
                {
                    id = id * 62 + url[i] - 'A' + 26;
                }

                else if (url[i] >= '0' && url[i] <= '9')
                {
                    id = id * 62 + url[i] - '0' + 52;
                }

                else
                {
                    id = -1;
                }
            }

            return id;
        }
    }
}
